data_settings:
  days_back: 2
  initial_days_back: 5
  limit: 10000
  dataset: "pjm_standardized_5_min"
  columns:
    - "interval_start_utc"
    - "interval_end_utc"
    - "load.comed"
  timezones:
    source: "UTC"
    target: "America/Chicago"

posting:
  interval_hours: 4
  include_images: true
  retry_attempts: 3
  include_source_link: true
