data_settings:
  days_back: 1 # how far back the post should analyze
  initial_days_back: 3 # when you load the app for the first time this is how far back it pulls data for
  limit: 10000 # limit gridstatus data volume
  dataset: "pjm_standardized_5_min" # gridstatus data set
  columns:
    - "interval_start_utc"
    - "interval_end_utc"
    - "load.comed"
  timezones:
    source: "UTC"
    target: "America/Chicago"

visualization:
  chart_width: 12
  chart_height: 6
  dpi: 300
  hour_interval: 3

posting:
  interval_hours: 4
  include_images: true
  retry_attempts: 3
  include_source_link: true
  processes:
    load:
      enabled: true
    nuclear:
      enabled: true
      require_recent_nrc_data: true  # New setting to require NRC data be less than 24 hours old

nuclear_data:
  nrc:
    url: "https://www.nrc.gov/reading-rm/doc-collections/event-status/reactor-status/powerreactorstatusforlast365days.txt"
    plants:
      - "Braidwood 1"
      - "Braidwood 2"
      - "Byron 1"
      - "Byron 2"
      - "Dresden 2"
      - "Dresden 3"
      - "LaSalle 1"
      - "LaSalle 2"
      - "Quad Cities 1"
      - "Quad Cities 2"
  eia:
    plant_ids: # found them here https://www.eia.gov/opendata/browser/electricity/operating-generator-capacity?frequency=monthly&data=net-summer-capacity-mw;net-winter-capacity-mw;&facets=plantid;&plantid=6022;6023;6026;869;&start=2023-01&end=2024-09&sortColumn=period;&sortDirection=desc;
      - "6022"  # Braidwood
      - "6023"  # Byron
      - "869"   # Dresden
      - "6026"  # LaSalle
      - "880"  # Quad Cities
    plant_mappings:
      Braidwood:
        nrc_names: ["Braidwood 1", "Braidwood 2"]
        eia_plant_id: "6022"
      Byron:
        nrc_names: ["Byron 1", "Byron 2"]
        eia_plant_id: "6023"
      Dresden:
        nrc_names: ["Dresden 2", "Dresden 3"]
        eia_plant_id: "869"
      LaSalle:
        nrc_names: ["LaSalle 1", "LaSalle 2"]
        eia_plant_id: "6026"
      Quad Cities:
        nrc_names: ["Quad Cities 1", "Quad Cities 2"]
        eia_plant_id: "880"
